public enum ActionType
{
    //SIMPLES
    GAIN_BUBBLE,
    LOSE_BUBBLE,
    GAIN_MOXIE,
    LOSE_MOXIE,
    GAIN_HIJINKS,
    LOSE_HIJINKS,
    DO_NOTHING,
    
    //GAIN BUBBLES
    GAIN_BUBBLE_LOSE_MOXIE,
    GAIN_BUBBLE_LOSE_HIJINKS,
    GAIN_BUBBLE_GAIN_MOXIE,
    GAIN_BUBBLE_GAIN_HIJINKS,
    
    //LOSE BUBBLES
    LOSE_BUBBLE_GAIN_HIJINKS,
    LOSE_BUBBLE_GAIN_MOXIE,
    LOSE_BUBBLE_LOSE_MOXIE,
    LOSE_BUBBLE_LOSE_HIJINKS,
    
    // NON-BUBBLE
    GAIN_MOXIE_GAIN_HIJINKS,
    LOSE_MOXIE_LOSE_HIJINKS,
    GAIN_HIJINKS_LOSE_MOXIE,
    GAIN_MOXIE_LOSE_HIJINKS,
}